
### 틀린 답 ###
# SELECT HOST_ID
# FROM PLACES
# GROUP BY HOST_ID,
# HAVING COUNT(HOST_ID) > 1;

### 정답 ###
SELECT *
FROM PLACES 
WHERE HOST_ID IN 
(
    (SELECT HOST_ID FROM PLACES GROUP BY HOST_ID HAVING count(HOST_ID) > 1)
) 